import { Type, Minus, Square, Circle, Star, Lock, Trash2, Copy, Eye, EyeOff } from "lucide-react"
import { cn } from "@/lib/utils"
import type { CertificateTemplate, TemplateElement } from "@/lib/template-editor"
import {
  defaultTextElement, defaultHeadingElement, defaultDivider,
  defaultRectangle, defaultEllipse, defaultLogoElement,
} from "@/lib/template-editor"

interface LayerPanelProps {
  template: CertificateTemplate
  selectedId: string | null
  onSelectElement: (id: string) => void
  onUpdateElement: (id: string, changes: Partial<TemplateElement>) => void
  onRemoveElement: (id: string) => void
}

export function ElementsPanel({ template, selectedId, onSelectElement, onUpdateElement, onRemoveElement }: LayerPanelProps) {
  const addElement = (factory: () => TemplateElement | TemplateElement[]) => {
    const result = factory()
    const els = Array.isArray(result) ? result : [result]
    els.forEach(el => {
      // IDs will be auto-generated by the editor, just add to template
      template.elements.push(el)
    })
  }

  const ADD_ITEMS = [
    { label: "Heading", icon: <span className="font-black text-[11px]">H</span>, make: () => defaultHeadingElement() },
    { label: "Text", icon: <Type size={13} />, make: () => defaultTextElement({ content: "Click to edit text" }) },
    { label: "Token", icon: <span className="text-[9px] font-bold font-mono">{"{T}"}</span>, make: () => defaultTextElement({ content: "{FullName}", fontSize: 22, fontWeight: "700" }) },
    { label: "Divider", icon: <Minus size={13} />, make: () => defaultDivider() },
    { label: "Rectangle", icon: <Square size={13} />, make: () => defaultRectangle() },
    { label: "Ellipse", icon: <Circle size={13} />, make: () => defaultEllipse() },
    { label: "Logo", icon: <Star size={13} />, make: () => defaultLogoElement("logo_organizer") },
  ]

  return (
    <div className="flex flex-col h-full gap-2 p-3 bg-white border-l">
      {/* Elements list */}
      <div className="flex-1 overflow-y-auto space-y-1">
        <div className="text-xs font-semibold text-gray-600 mb-2">Layers</div>
        {template.elements.map((el) => (
          <div
            key={el.id}
            onClick={() => onSelectElement(el.id)}
            className={cn(
              "flex items-center justify-between gap-1 px-2 py-1.5 rounded text-xs cursor-pointer transition-colors",
              selectedId === el.id ? "bg-blue-100 text-blue-900" : "bg-gray-50 hover:bg-gray-100"
            )}
          >
            <span className="truncate flex-1">{el.type === "text" ? (el as any).content?.slice(0, 20) : el.type}</span>
            <div className="flex items-center gap-0.5">
              <button
                onClick={(e) => {
                  e.stopPropagation()
                  onUpdateElement(el.id, { locked: !(el as any).locked })
                }}
                className="p-0.5 hover:bg-white rounded"
                title={el.locked ? "Unlock" : "Lock"}
              >
                {el.locked ? <Lock size={12} /> : <EyeOff size={12} className="opacity-50" />}
              </button>
              <button
                onClick={(e) => {
                  e.stopPropagation()
                  onUpdateElement(el.id, { hidden: !(el as any).hidden })
                }}
                className="p-0.5 hover:bg-white rounded"
                title={(el as any).hidden ? "Show" : "Hide"}
              >
                {(el as any).hidden ? <EyeOff size={12} /> : <Eye size={12} />}
              </button>
              <button
                onClick={(e) => {
                  e.stopPropagation()
                  onRemoveElement(el.id)
                }}
                className="p-0.5 hover:bg-red-100 text-red-600 rounded"
                title="Delete"
              >
                <Trash2 size={12} />
              </button>
            </div>
          </div>
        ))}
      </div>

      {/* Add buttons */}
      <div className="border-t pt-2">
        <div className="text-xs font-semibold text-gray-600 mb-2">Add Element</div>
        <div className="grid grid-cols-4 gap-1">
          {ADD_ITEMS.map((item) => (
            <button
              key={item.label}
              onClick={() => addElement(item.make)}
              className="flex flex-col items-center justify-center gap-1 p-2 rounded border border-gray-200 hover:border-blue-400 hover:bg-blue-50 transition-colors text-xs text-gray-600 hover:text-blue-600"
              title={item.label}
            >
              {item.icon}
              <span className="text-[10px]">{item.label}</span>
            </button>
          ))}
        </div>
      </div>
    </div>
  )
}
